CREATE OR REPLACE TRIGGER tr_Employee_Details
BEFORE INSERT OR DELETE OR UPDATE ON Employee_Details
FOR EACH ROW
ENABLE
BEGIN

  IF INSERTING THEN
    DBMS_OUTPUT.PUT_LINE('one line inserted');
  ELSIF DELETING THEN
    DBMS_OUTPUT.PUT_LINE('one line Deleted');
  ELSIF UPDATING THEN
    DBMS_OUTPUT.PUT_LINE('one line Updated');
  END IF;
END;
/